### ISSUE TITLE
Undefined name 'utxo_id' in web-smart_contract/serve.py

### ISSUE THREAD

**Issue by cclauss** [sixstars/starctf2018#1]
$ __python2 -m flake8 . --count --show-source --statistics --select=E901,E999,F821,F822,F823__
```
./web-smart_contract/serve.py:277:76: F821 undefined name 'utxo_id'
				raise Exception("invalid id of output utxo. utxo id({}) exists".format(utxo_id))
                                                                           ^
1     F821 undefined name 'utxo_id'
1
```

Should this be __new_id__?
* https://github.com/sixstars/starctf2018/blob/master/web-smart_contract/serve.py#L275-L277

**Comment by Septyem** [comment]
I think you are right according to the context. Since the server is unlikely to execute this line (and this line should raise an exception already) it didn't cause any trouble during competition, and no one noticed it before.
